# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
    - name: Commit files
      run: |
        git config --local user.email "ryanherford@gmail.com"
        git config --global user.name "Geniusflip"
        git remote add blog https://Geniusflip:${{ secrets.PASSWORD }}@github.com/Geniusflip/quickblopg.git
        echo 'here'
        git pull origin master
        git checkout master
        echo 'pulling minesweeper'
        git pull blog minesweeper --allow-unrelated-histories
        echo 'checking out'
        git checkout -b blog/minesweeper
        echo 'reseting history'
        git reset --hard origin/master
        git push --force

