# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
    - name: Commit files
      run: |
        git config --local user.email "ryanherford@gmail.com"
        git config --local user.name "GitHub Action"
    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: https://github.com/Geniusflip/quickblopg.git
        BRANCH: minesweeper
        FOLDER: .
        SSH_PRIVATE_KEY: ${{ secrets.TOKEN }}
